// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaUp5GLkp4e8t4yk4CwswKWWxXNXSteZ4',
    appId: '1:184248206055:web:ecd8eddec03558b55dd842',
    messagingSenderId: '184248206055',
    projectId: 'sahilproject-ac4f2',
    authDomain: 'sahilproject-ac4f2.firebaseapp.com',
    databaseURL: 'https://sahilproject-ac4f2-default-rtdb.firebaseio.com',
    storageBucket: 'sahilproject-ac4f2.firebasestorage.app',
    measurementId: 'G-5C07YZR8FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB85LJvXg2u9sKwABUm2pC2BqA5ZQRpm-M',
    appId: '1:184248206055:android:55702b16db11c2f35dd842',
    messagingSenderId: '184248206055',
    projectId: 'sahilproject-ac4f2',
    databaseURL: 'https://sahilproject-ac4f2-default-rtdb.firebaseio.com',
    storageBucket: 'sahilproject-ac4f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB93_EzAfGq7WjNYgEJUFU9xmZssULSLwI',
    appId: '1:184248206055:ios:44a752fad9453be15dd842',
    messagingSenderId: '184248206055',
    projectId: 'sahilproject-ac4f2',
    databaseURL: 'https://sahilproject-ac4f2-default-rtdb.firebaseio.com',
    storageBucket: 'sahilproject-ac4f2.firebasestorage.app',
    iosBundleId: 'com.example.sixWeeks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB93_EzAfGq7WjNYgEJUFU9xmZssULSLwI',
    appId: '1:184248206055:ios:44a752fad9453be15dd842',
    messagingSenderId: '184248206055',
    projectId: 'sahilproject-ac4f2',
    databaseURL: 'https://sahilproject-ac4f2-default-rtdb.firebaseio.com',
    storageBucket: 'sahilproject-ac4f2.firebasestorage.app',
    iosBundleId: 'com.example.sixWeeks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaUp5GLkp4e8t4yk4CwswKWWxXNXSteZ4',
    appId: '1:184248206055:web:d20cc9c8f89cb7f85dd842',
    messagingSenderId: '184248206055',
    projectId: 'sahilproject-ac4f2',
    authDomain: 'sahilproject-ac4f2.firebaseapp.com',
    databaseURL: 'https://sahilproject-ac4f2-default-rtdb.firebaseio.com',
    storageBucket: 'sahilproject-ac4f2.firebasestorage.app',
    measurementId: 'G-FC9WNLM4H8',
  );
}
